//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8058_Assignment_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Requirments { get; set; }
        public int Salary { get; set; }
    
        public virtual Vacancy Vacancy { get; set; }
        public virtual Applicant Applicant { get; set; }
    }
}
