//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8058_Assignment_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public int JobID { get; set; }
        public string JobDescription { get; set; }
        public int Salary { get; set; }
        public int NoOfEmplyeeRequired { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
