//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8058_Assignment_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works_On
    {
        public int EmployeeID { get; set; }
        public int ProjectID { get; set; }
        public int Working_Hours { get; set; }
        public int PerHourWage { get; set; }
        public int Salary { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
    }
}
